### PR TITLE
added bower.json, moved tests and demos into separate dirs

### PR DESCRIPTION
**Pull request by alexey-sh**

### CODE REVIEW

**Comment by summera** [comment]
@alexey-sh Thanks for this! :smile:  I started it a while back for a class I was taking and haven't given it the love :heart: it needs. I think I'm going to spend some time today working on some updates!

I'd really like to redo all the tests and use mocha/chai. In addition I want to redo some things, including using promises to mitigate the [Pyramid of Doom](http://calculist.org/blog/2011/12/14/why-coroutines-wont-work-on-the-web/). Then I'd like to release a version on Bower :100: 

Would you be interested in helping me with this?

**Comment by alexey-sh** [comment]
@summera thanks for the response! 
Do I understand correctly that you want to use coroutines? In that case I think that promises is more useful thing for this library. 
Additionally I want to advise to use the coffescript.

**Comment by summera** [comment]
I'd like to use [Q](https://github.com/kriskowal/q) for promises. 
I don't think there is a need for coffeescript here.

**Comment by alexey-sh** [comment]
[Q](https://github.com/kriskowal/q) looks as awesome thing! 
So my wish is too small to help with Q(I'm sorry:worried:). But I'm interested to write backbone adapter which can store files in filestorage(using your cool library). Like a [Backbone.dualStorage](https://github.com/nilbus/Backbone.dualStorage) or [Backbone.ChromeStorage](https://github.com/scryptmouse/Backbone.ChromeStorage)

**Pull request closed without merging**
